# Evaluation and vizualisation

## Imports

In [ ]:
from tracNet import TracNet
from data_preparation import matFiles_to_npArray
from data_vizualisation import plotCell
from training_and_evaluation import test

import matplotlib.pyplot as plt
import numpy as np
import torch

from gc import collect

%matplotlib notebook

Set seeds for reproducability.

In [ ]:
random_seed = 1
np.random.seed(random_seed)
torch.manual_seed(random_seed)
torch.cuda.manual_seed(random_seed)
torch.backends.cudnn.benchmark = False

Use CUDA if available.

In [ ]:
collect()
torch.cuda.empty_cache()
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
print(f"Running on device: {device}")

## Evaluation

Specify paths to test data.

In [ ]:
# Test data
test_dspl_path = '/home/alexrichard/LRZ Sync+Share/ML in Physics/Repos/DL-TFM-main/test/generic/testData104/dspl'
test_trac_path = '/home/alexrichard/LRZ Sync+Share/ML in Physics/Repos/DL-TFM-main/test/generic/testData104/trac'
# test_dspl_path = '/Users/alex/LRZ Sync+Share/ML in Physics/Repos/DL-TFM-main/test/generic/testData104/dspl'
# test_trac_path = '/Users/alex/LRZ Sync+Share/ML in Physics/Repos/DL-TFM-main/test/generic/testData104/trac'

Create `ndarrays` of `dicts` containing either the inputs or targets.

In [ ]:
X_test = matFiles_to_npArray(test_dspl_path) # each dict has keys ['brdx', 'brdy', 'dspl', 'name']
y_test = matFiles_to_npArray(test_trac_path) # each dict has keys ['brdx', 'brdy', 'trac', 'name']

Load model.

In [ ]:
model = TracNet(n_channels=1).double()
model.load_state_dict(torch.load('/home/alexrichard/LRZ Sync+Share/ML in Physics/Models/TracNet104-2022-May-12 19:12:09.pth'), strict=False)

Evaluate the model on the test set.

In [ ]:
avg_error, errors = test(X_test, y_test, model, 10670, plot=False)

In [ ]:
avg_error

In [ ]:
dict(sorted(errors.items()))

In [ ]:
errors

## 4. Data visualization

In [ ]:
brdx = X_test[0]['brdx'][0]
brdy = X_test[0]['brdy'][0]
dspl = X_test[0]['dspl']
dspl_x = X_test[0]['dspl'][:,:,0]
dspl_y = X_test[0]['dspl'][:,:,1]

In [ ]:
plt.quiver(dspl_x.T, dspl_y.T)

In [ ]:
def plotDspl(dspl, brdx=[], brdy=[], scale=0, thinning=1):
    # prepare
    '''
    J, I = np.meshgrid(np.arange(0, dspl.shape[1]), np.arange(0, dspl.shape[0]))
    indx = np.floor(np.arange(0, I.size, thinning)).astype(int)
    print(indx.shape)
    D1 = dspl[:,:,0][indx]
    I = I[indx]
    
    indx = np.floor(np.arange(0, J.size, thinning)).astype(int)
    D2 = dspl[:,:,1][indx]
    J = J[indx]
    '''
    # quiver plot
    plt.plot(brdx, brdy)
    plt.quiver(dspl_x.T * scale, dspl_y.T * scale)
    plt.show()
    
    # heat map

In [ ]:
plotDspl(dspl, brdx, brdy)

In [ ]:
indx

In [ ]:
np.ceil(np.arange(1, 80, 0.5)).astype(int)

In [ ]:
np.arange?

In [ ]:
J, I = np.meshgrid(np.arange(0, dspl.shape[1]), np.arange(0, dspl.shape[0]))

In [ ]:
plt.show()

In [ ]:
np.arange(0,10)

In [ ]:
indx = np.ceil(np.arange(0, I.size, thinning))

In [ ]:
np.arange(1, 10, 0.5)

In [169]:
np.ceil(np.arange(1, 80, 0.5)).astype(int)

array([ 1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,  9,  9,
       10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16, 16, 17, 17, 18,
       18, 19, 19, 20, 20, 21, 21, 22, 22, 23, 23, 24, 24, 25, 25, 26, 26,
       27, 27, 28, 28, 29, 29, 30, 30, 31, 31, 32, 32, 33, 33, 34, 34, 35,
       35, 36, 36, 37, 37, 38, 38, 39, 39, 40, 40, 41, 41, 42, 42, 43, 43,
       44, 44, 45, 45, 46, 46, 47, 47, 48, 48, 49, 49, 50, 50, 51, 51, 52,
       52, 53, 53, 54, 54, 55, 55, 56, 56, 57, 57, 58, 58, 59, 59, 60, 60,
       61, 61, 62, 62, 63, 63, 64, 64, 65, 65, 66, 66, 67, 67, 68, 68, 69,
       69, 70, 70, 71, 71, 72, 72, 73, 73, 74, 74, 75, 75, 76, 76, 77, 77,
       78, 78, 79, 79, 80])

In [166]:
np.arange?

In [163]:
J, I = np.meshgrid(np.arange(0, dspl.shape[1]), np.arange(0, dspl.shape[0]))

In [209]:
plt.show()

In [175]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
indx = np.ceil(np.arange(0, I.size, thinning))

NameError: name 'thinning' is not defined

In [158]:
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])